#!/hint/bash
# calamares config switcher configuration (AI-2)

title="Install AI-2"

text="Select installer configuration:<br><br>Online is experimental, go with offline.<br>"

configs=(offline online)
