#!/usr/bin/env python3
"""Render the AI-2 GRUB boot-menu background as SVG: the COMPACT lockup (the
rounded box with `> AI-2 █`, same geometry as the wallpaper) with a soft
phosphor glow, sitting above the menu panel on the near-black canvas.
No tagline (dropped everywhere 2026-08-16). Rafael 2026-08-16: use the boxed
wallpaper logo here too, not the earlier neon-outline lettering.

  gen-background.py OUT.svg [scale] [box_top]

scale    size of the lockup relative to the wallpaper lockup (default 0.8 →
         608x141 px box in the 1024x768 canvas)
box_top  y of the box top edge (default 45; the menu panel starts at 28% = 215)
"""
import sys

out = sys.argv[1]
s = float(sys.argv[2]) if len(sys.argv) > 2 else 0.8
top = float(sys.argv[3]) if len(sys.argv) > 3 else 45
W, H = 1024, 768                       # GRUB_GFXMODE used by Artix/AI-2 (ISO + installed)
# wallpaper lockup geometry (000/design/ai2-wallpaper.svg), scaled by s
bw, bh, rx, sw = 760 * s, 176 * s, 34 * s, 7 * s
x0 = (W - bw) / 2
fs = 96 * s
svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}">
  <!-- AI-2 GRUB background, generated by gen-background.py (scale={s}, top={top}) -->
  <defs>
    <radialGradient id="vig" cx="50%" cy="50%" r="70%">
      <stop offset="0" stop-color="#101814"/>
      <stop offset="1" stop-color="#0B0F0D"/>
    </radialGradient>
    <filter id="glow" x="-20%" y="-50%" width="140%" height="200%"><feGaussianBlur stdDeviation="{14 * s:.1f}"/></filter>
    <g id="mark" font-family="DejaVu Sans Mono" font-weight="bold" font-size="{fs:.1f}">
      <rect x="{x0:.1f}" y="{top:.1f}" width="{bw:.1f}" height="{bh:.1f}" rx="{rx:.1f}" fill="none" stroke="#35D07F" stroke-width="{sw:.1f}"/>
      <text x="{x0 + 56 * s:.1f}" y="{top + 122 * s:.1f}" fill="#35D07F" xml:space="preserve">&gt; AI-2 </text>
      <rect x="{x0 + 640 * s:.1f}" y="{top + 44 * s:.1f}" width="{56 * s:.1f}" height="{88 * s:.1f}" rx="{5 * s:.1f}" fill="#35D07F"/>
    </g>
  </defs>
  <rect width="{W}" height="{H}" fill="url(#vig)"/>
  <use href="#mark" filter="url(#glow)" opacity="0.45"/>
  <use href="#mark"/>
</svg>
'''
open(out, "w").write(svg)
