#!/usr/bin/env python3
"""Render the AI-2 GRUB boot-menu artwork as SVG. Two files since 2026-08-26:

  background.svg  the near-black vignette ONLY (1024x768). GRUB stretches the
                  desktop image to fill whatever mode it runs in; a stretched
                  vignette is invisible, a stretched logo is not (rafaminu-pc's
                  1366x768 panel showed the box visibly widened), so the mark
                  no longer lives in the background.
  logo.svg        the COMPACT lockup (`> AI-2 █`, wallpaper geometry) with its
                  soft phosphor glow on a transparent canvas. theme.txt places
                  the rendered PNG (ai2-logo.png) at its natural pixel size, so
                  it stays undistorted at any resolution/aspect ratio. Keep
                  theme.txt's image width/height/left in sync with the LOGO
                  CANVAS size this script prints.

  gen-background.py OUTDIR [scale]

scale  size of the lockup relative to the wallpaper lockup (default 0.65 ->
       494x114 px box; was 0.8 until 2026-08-26, Rafael: reduce it a little)
"""
import os
import sys

outdir = sys.argv[1]
s = float(sys.argv[2]) if len(sys.argv) > 2 else 0.65
W, H = 1024, 768                       # background canvas; GRUB stretches it

bg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}">
  <!-- AI-2 GRUB background (vignette only), generated by gen-background.py -->
  <radialGradient id="vig" cx="50%" cy="50%" r="70%">
    <stop offset="0" stop-color="#101814"/>
    <stop offset="1" stop-color="#0B0F0D"/>
  </radialGradient>
  <rect width="{W}" height="{H}" fill="url(#vig)"/>
</svg>
'''
open(os.path.join(outdir, "background.svg"), "w").write(bg)

# wallpaper lockup geometry (000/design/ai2-wallpaper.svg), scaled by s,
# on a transparent canvas with margin m so the glow is not clipped
m = 40
bw, bh, rx, sw = 760 * s, 176 * s, 34 * s, 7 * s
cw, ch = round(bw + 2 * m), round(bh + 2 * m)
fs = 96 * s
logo = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{cw}" height="{ch}" viewBox="0 0 {cw} {ch}">
  <!-- AI-2 GRUB logo, generated by gen-background.py (scale={s}) -->
  <defs>
    <filter id="glow" x="-20%" y="-50%" width="140%" height="200%"><feGaussianBlur stdDeviation="{14 * s:.1f}"/></filter>
    <g id="mark" font-family="DejaVu Sans Mono" font-weight="bold" font-size="{fs:.1f}">
      <rect x="{m:.1f}" y="{m:.1f}" width="{bw:.1f}" height="{bh:.1f}" rx="{rx:.1f}" fill="none" stroke="#35D07F" stroke-width="{sw:.1f}"/>
      <text x="{m + 56 * s:.1f}" y="{m + 122 * s:.1f}" fill="#35D07F" xml:space="preserve">&gt; AI-2 </text>
      <rect x="{m + 640 * s:.1f}" y="{m + 44 * s:.1f}" width="{56 * s:.1f}" height="{88 * s:.1f}" rx="{5 * s:.1f}" fill="#35D07F"/>
    </g>
  </defs>
  <use href="#mark" filter="url(#glow)" opacity="0.45"/>
  <use href="#mark"/>
</svg>
'''
open(os.path.join(outdir, "logo.svg"), "w").write(logo)
print(f"LOGO CANVAS {cw}x{ch} (box {bw:.0f}x{bh:.0f}); theme.txt: width={cw} height={ch} left=50%-{cw // 2}")
