#!/usr/bin/env python3
"""Render the AI-2 GRUB boot-menu background as SVG: the mark `> AI-2 █` as
dim neon tube lettering (outline + soft phosphor glow) on the near-black
canvas. No tagline on purpose (Rafael, 2026-08-16): as a background the mark
stands alone.

  gen-background.py OUT.svg [dim] [y_center] [font_px]

dim       overall brightness of the mark, 0-1 (default 0.55, well below the
          Artix neon)
y_center  vertical center of the mark in the 1024x768 canvas (default 125:
          the mark sits ABOVE the menu panel, fully visible, chosen by Rafael
          2026-08-16 over the ghosted-behind-the-menu variant)
font_px   font size in px (default 140)
"""
import sys

out = sys.argv[1]
dim = float(sys.argv[2]) if len(sys.argv) > 2 else 0.55
yc = int(sys.argv[3]) if len(sys.argv) > 3 else 125
fs = int(sys.argv[4]) if len(sys.argv) > 4 else 140
W, H = 1024, 768                       # GRUB_GFXMODE used by Artix/AI-2 (ISO + installed)
cw = fs * 0.602                        # DejaVu Sans Mono advance width
text = "> AI-2 "
tw = cw * len(text)
cur_w, cur_h = cw * 0.85, fs * 0.78    # block cursor
total = tw + cur_w
x0 = (W - total) / 2
baseline = yc + fs * 0.36              # visually center the cap height
cur_x = x0 + tw
cur_y = baseline - cur_h
svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}">
  <!-- AI-2 GRUB background, generated by gen-background.py (dim={dim}, y={yc}, font={fs}) -->
  <defs>
    <radialGradient id="vig" cx="50%" cy="50%" r="70%">
      <stop offset="0" stop-color="#101814"/>
      <stop offset="1" stop-color="#0B0F0D"/>
    </radialGradient>
    <filter id="glow-far" x="-30%" y="-60%" width="160%" height="220%"><feGaussianBlur stdDeviation="26"/></filter>
    <filter id="glow-near" x="-30%" y="-60%" width="160%" height="220%"><feGaussianBlur stdDeviation="7"/></filter>
    <g id="mark" fill="none" stroke-linejoin="round" stroke-linecap="round">
      <text x="{x0:.1f}" y="{baseline:.1f}" font-family="DejaVu Sans Mono" font-weight="bold" font-size="{fs}" xml:space="preserve">{text}</text>
      <rect x="{cur_x:.1f}" y="{cur_y:.1f}" width="{cur_w:.1f}" height="{cur_h:.1f}" rx="6"/>
    </g>
  </defs>
  <rect width="{W}" height="{H}" fill="url(#vig)"/>
  <g opacity="{dim}">
    <use href="#mark" stroke="#35D07F" stroke-width="22" filter="url(#glow-far)" opacity="0.55"/>
    <use href="#mark" stroke="#35D07F" stroke-width="10" filter="url(#glow-near)" opacity="0.7"/>
    <use href="#mark" stroke="#8CEBB5" stroke-width="4"/>
  </g>
</svg>
'''
open(out, "w").write(svg)
