#!/usr/bin/env python3
"""Write one PKGBUILD per Knowledge Pack that ships with AI-2.

The packages carry exactly the files the catalog publishes: same URL, same
SHA-256, so what a machine gets from the ISO is byte-for-byte what it would
have got with `ai-2 knowledge install ai2-help`. Generating them from
ai2/data/packs.yml is what keeps that true; a test fails when the generated
files no longer match the catalog.

  python3 tools/render-pack-packages.py            write them
  python3 tools/render-pack-packages.py --check    say whether they are current
"""
from __future__ import annotations

import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
CATALOG = ROOT / "ai2/data/packs.yml"
# The packs that come with AI-2 (Rafael, 2026-09-20: all three). A pack not
# listed here is still installable by name; it just does not ship.
SHIPPED = ("ai2-help", "everyday", "linux-essentials")

TEMPLATE = """# Maintainer: Rafael Minuesa <rafael.minuesa@gmail.com>
# Generated by tools/render-pack-packages.py from ai2/data/packs.yml.
# Do not edit by hand: the file this installs is the one the catalog
# publishes, same URL and same SHA-256, so a pack that comes with AI-2 is
# byte-for-byte the pack `ai-2 knowledge install {pack_id}` would fetch.

pkgname={pkgname}
pkgver={pkgver}
pkgrel={pkgrel}
pkgdesc="{pkgdesc}"
arch=('any')
url="https://github.com/ProWoos-Devs/ai2-knowledge"
license=('{license}')
depends=('ai-2')
source=("{pkgname}-$pkgver.ai2pack::{url}")
sha256sums=('{sha256}')
noextract=("{pkgname}-$pkgver.ai2pack")

package() {{
  local dest="$pkgdir/usr/share/ai2/doc/{pack_id}"
  install -dm755 "$dest"
  # a pack is a zip of manifest.yml + index.sqlite
  bsdtar -xf "$srcdir/{pkgname}-$pkgver.ai2pack" -C "$dest" manifest.yml index.sqlite
  chmod 644 "$dest/manifest.yml" "$dest/index.sqlite"
  # the record `ai-2 knowledge list` reads to say where a pack came from
  printf '%s\\n' "from: AI-2 itself" "id: {pack_id}" "version: {version}" \\
      "sha256: {sha256}" > "$dest/origin.yml"
  chmod 644 "$dest/origin.yml"
}}
"""


def package_name(pack_id: str) -> str:
    return pack_id if pack_id.startswith("ai2-") else "ai2-" + pack_id


def render(entry: dict) -> tuple[str, str]:
    name = package_name(entry["id"])
    text = TEMPLATE.format(
        pkgname=name,
        pack_id=entry["id"],
        pkgver=str(entry["version"]).replace("-", "."),
        pkgrel=int(entry.get("revision") or 1),
        pkgdesc=f"{entry['title']} Knowledge Pack for AI-2 ({entry.get('parts')} parts, "
                f"{', '.join(entry.get('languages') or [])})",
        license=entry.get("license"),
        url=entry["url"],
        sha256=entry["sha256"],
        version=entry["version"],
    )
    return name, text


def main() -> int:
    check = "--check" in sys.argv[1:]
    entries = {p["id"]: p for p in yaml.safe_load(CATALOG.read_text())["packs"]}
    missing = [p for p in SHIPPED if p not in entries]
    if missing:
        print(f"the catalog has no entry for {', '.join(missing)}")
        return 1
    stale = []
    for pack_id in SHIPPED:
        name, text = render(entries[pack_id])
        path = ROOT / "packaging" / name / "PKGBUILD"
        if check:
            if not path.exists() or path.read_text() != text:
                stale.append(name)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print(f"{path.relative_to(ROOT)}: {entries[pack_id]['version']} revision "
              f"{entries[pack_id].get('revision') or 1}")
    if check:
        if stale:
            print("out of step with the catalog: " + ", ".join(stale)
                  + "\nrun: python3 tools/render-pack-packages.py")
            return 1
        print(f"the {len(SHIPPED)} pack packages match the catalog")
    return 0


if __name__ == "__main__":
    sys.exit(main())
